name: py-fundamentals
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab=4.*
  - jupyter
  - ipykernel
  - requests
  - beautifulsoup4
  - pip
  - pip:
      - pytest
      - nbmake
      - nbstripout
      - nbqa
      - flake8